# Generated by Django 4.2.9 on 2024-02-19 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseSite', '0003_alter_pokemon_secondarytype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='secondaryType',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondaryType', to='baseSite.type'),
        ),
    ]
