# Generated by Django 4.2.9 on 2024-02-19 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseSite', '0005_alter_quote_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='quote',
            field=models.CharField(max_length=5000),
        ),
    ]
